# Generated by Django 5.1.1 on 2024-09-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jobmodel_jobapplimodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='job_type',
            new_name='company_type',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('jobseeker', 'Jobseeker')], max_length=100, null=True),
        ),
    ]
