# Generated by Django 5.1.1 on 2024-09-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_job_type_jobmodel_company_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobAppliModel',
        ),
    ]
