# Generated by Django 5.1.1 on 2024-09-26 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_jobapplimodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resume', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('Cover', models.CharField(blank=True, max_length=255, null=True)),
                ('Full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Work_Experience', models.TextField(blank=True, null=True)),
                ('Expected_Salary', models.PositiveIntegerField(blank=True, null=True)),
                ('Skill', models.CharField(blank=True, max_length=100, null=True)),
                ('Linkdin_URL', models.URLField(blank=True, max_length=100, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
