# Generated by Django 5.1.1 on 2024-10-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_custom_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_user',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='custom_user',
            old_name='pic',
            new_name='profile_picture',
        ),
    ]
